[package]
name = "e57"
version = "0.5.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/cry-inc/e57"
documentation = "https://docs.rs/e57"
license = "MIT"
keywords = ["e57", "lidar", "pointclouds", "laserscanning", "geospatial"]
categories = ["parser-implementations", "science::geo"]
description = "A pure Rust library for reading and writing E57 files with point clouds and related image data."
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
]

[dependencies]
memmap2 = "0.6.2"
roxmltree = "0.18"
